version: '3.8'
services:
  cmdb-mcp:
    build: .
    image: cmdb-mcp:latest
    ports:
      - "9101:9101"
    environment:
      - CMDB_DB_PATH=/data/cmdb.sqlite3
      - AIOPS_LOG_DIR=/data/logs
      - REQUIRE_AUTH=${REQUIRE_AUTH:-1}
      - MCP_TOKEN=${MCP_TOKEN:-secret123}
    volumes:
      - ./data:/data
