version: '3.8'
services:
  cmdb-mcp:
    build: .
    image: cmdb-mcp
    container_name: cmdb-mcp
    working_dir: /app/cmdb-mcp
    ports:
      - "9001:9001"
    environment:
      AIOPS_LOG_DIR: "/app/cmdb-mcp/logs"
      REQUIRE_AUTH: "1"           # デフォルトを固定
      MCP_TOKEN: "secret123"      # デフォルトを固定。機密なら後述の方法で注入
#      CMDB_DB: "/app/cmdb-mcp/rag.db"      # ← これを“唯一の参照”にする
      CMDB_DB: "/app/cmdb-mcp/rag.db"        # ← 参照パスを /data 側に移動（ここだけを見るように）
    volumes:
      - ./rag.db:/app/cmdb-mcp/rag.db:ro   # ← “濃い”rag.db を明示#      - ./logs:/cmdb-mcpapp/logs
      - ./:/app/cmdb-mcp:rw
    networks:
      - mgmtnet

networks:
  mgmtnet:
    external: true
