version: '3.8'
services:
  cmdb-mcp:
    build: .
    image: cmdb-mcp
    container_name: cmdb-mcp
    working_dir: /app/cmdb-mcp
    ports:
      - "9001:9001"
    environment:
      AIOPS_LOG_DIR: "/app/cmdb-mcp/logs"
      REQUIRE_AUTH: "1"           # デフォルトを固定
      MCP_TOKEN: "secret123"      # デフォルトを固定。機密なら後述の方法で注入
      CMDB_DB: "/app/cmdb-mcp/rag.db"    # ← 参照パスを固定
      CMDB_DB_PATH: "/data/cmdb.sqlite3"
    volumes:
      - ./rag.db:/app/cmdb-mcp/rag.db
      - ./:/app/cmdb-mcp:rw
      - ./data:/data
#      - ./logs:/cmdb-mcpapp/logs
    networks:
      - mgmtnet

networks:
  mgmtnet:
    external: true
