version: '3.8'
services:
  cmdb-mcp:
    build: .
    image: cmdb-mcp
    container_name: cmdb-mcp
    ports:
      - "9101:9101"
    environment:
      - CMDB_DB_PATH=/data/cmdb.sqlite3
      - AIOPS_LOG_DIR=/app/logs
      - REQUIRE_AUTH=${REQUIRE_AUTH:-1}
      - MCP_TOKEN=${MCP_TOKEN:-secret123}
    volumes:
      - ./data:/data
      - ./logs:/app/logs
